default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: alexandar_epicodus_portfolio_development

test:
  <<: *default
  database: alexandar_epicodus_portfolio_test

production:
  <<: *default
  database: alexandar_epicodus_portfolio_production
  username: alexandar_epicodus_portfolio
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
